baseURL = "https://renatdk.github.io/go/public/"
languageCode = "ru-ru"
title = "Решения на golang"
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]

[params]
  description = "Лучшие решения которые я нашел. Если найдете лучше, пожалуйста, напишите мне ;)"
  copyright = "Пишет Ренат Дарыбаев"
